apiVersion: v1
kind: Service
metadata:
  name: fastify-app-svc
  labels:
    run: fastify
spec:
  selector:
    app: fastify
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort



kubectl apply --filename https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/eploy/recommended.yaml